// ============================================================
// 修仙功法数据库 - 收集自全网修仙小说
// 共收录 80 部功法，分为黄/玄/地/天/仙/圣 六阶
// 黄/玄/地/天/仙：凡人修仙传、斗破苍穹、遮天、完美世界、一念永恒、玄界之门
// 圣阶：封神演义、洪荒流、西游记等（真仙至准圣境界可用，修炼速度 8.0-15.0）
// ============================================================

const GONGFA_DATA = {

  // ============================================================
  // 黄阶功法（炼气期可用，修炼速度 1.0-1.5）
  // ============================================================
  huang: [
    {
      id: 'gf_changchun',
      name: '长春功',
      novel: '凡人修仙传',
      element: '木',
      grade: '黄阶',
      desc: '基础木属性功法，修炼后耳聪目明，提升感知力，体内灵力温润如春木常青',
      cultSpeed: 1.2,
      compBonus: 0,
      mindBonus: 2,
      atkBonus: 0,
      defBonus: 1,
      realmReq: 0,
      obtain: '师门',
      obtainDesc: '加入宗门后可在藏经阁领取'
    },
    {
      id: 'gf_mingshui',
      name: '溟水诀',
      novel: '凡人修仙传',
      element: '水',
      grade: '黄阶',
      desc: '水属性入门功法，修炼后体内灵力如潮水般绵延不绝，适合修炼水系法术',
      cultSpeed: 1.1,
      compBonus: 1,
      mindBonus: 1,
      atkBonus: 2,
      defBonus: 1,
      realmReq: 0,
      obtain: '师门',
      obtainDesc: '墨府修仙家族传承功法，入门弟子皆可修习'
    },
    {
      id: 'gf_yuhuo',
      name: '浴火术',
      novel: '完美世界',
      element: '火',
      grade: '黄阶',
      desc: '以火焰淬炼肉身的基础功法，能增强火属性抗性，修炼时需引火入体锻骨炼筋',
      cultSpeed: 1.3,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 3,
      defBonus: 2,
      realmReq: 0,
      obtain: '秘境',
      obtainDesc: '在火属性秘境中于岩浆湖底石碑上发现'
    },
    {
      id: 'gf_biyin',
      name: '碧音万波功',
      novel: '玄界之门',
      element: '水',
      grade: '黄阶',
      desc: '以音波为媒介驾驭水灵力的功法，修炼后可发出摄人心神的水波音攻，防不胜防',
      cultSpeed: 1.15,
      compBonus: 1,
      mindBonus: 1,
      atkBonus: 2,
      defBonus: 0,
      realmReq: 0,
      obtain: '拍卖',
      obtainDesc: '在坊市拍卖会上以低价购得残卷，后自行补全'
    },
    {
      id: 'gf_huoyuan',
      name: '火元经',
      novel: '玄界之门',
      element: '火',
      grade: '黄阶',
      desc: '凝聚火元力入体的基础功法，修炼后丹田中火元力充沛，火系法术威力大增',
      cultSpeed: 1.25,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 4,
      defBonus: 0,
      realmReq: 0,
      obtain: '师门',
      obtainDesc: '玄界宗门初级弟子修炼功法，入门考核通过即可领取'
    },
    {
      id: 'gf_chiyuan',
      name: '赤猿火经',
      novel: '玄界之门',
      element: '火',
      grade: '黄阶',
      desc: '仿上古赤猿吐纳之法，修炼后体质增强，拳脚附带灼热火焰，近战威力不俗',
      cultSpeed: 1.3,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 3,
      defBonus: 2,
      realmReq: 0,
      obtain: '秘境',
      obtainDesc: '赤猿洞府遗迹中石壁刻有此经，需以火灵力激活方可显形'
    },
    {
      id: 'gf_qisha',
      name: '七杀棍术',
      novel: '玄界之门',
      element: '金',
      grade: '黄阶',
      desc: '以杀伐之气驱动棍法的武技功法，七式连绵如杀神降世，攻势凌厉无匹',
      cultSpeed: 1.1,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 5,
      defBonus: 0,
      realmReq: 0,
      obtain: '掠夺',
      obtainDesc: '击败山贼头领后从其储物袋中搜得'
    },
    {
      id: 'gf_fengchi',
      name: '风驰十三式刀法',
      novel: '玄界之门',
      element: '风',
      grade: '黄阶',
      desc: '风属性刀法功法，十三式如疾风骤雨，修炼后刀速极快，可斩出风刃伤敌',
      cultSpeed: 1.15,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 4,
      defBonus: 0,
      realmReq: 0,
      obtain: '师门',
      obtainDesc: '师门武技堂第一层，外门弟子可用贡献点兑换'
    },
    {
      id: 'gf_suishi',
      name: '碎石拳',
      novel: '玄界之门',
      element: '土',
      grade: '黄阶',
      desc: '土属性拳法功法，以大地之力灌注双拳，一拳可碎巨石，防御力亦有所提升',
      cultSpeed: 1.2,
      compBonus: 0,
      mindBonus: 0,
      atkBonus: 3,
      defBonus: 3,
      realmReq: 0,
      obtain: '奇遇',
      obtainDesc: '在山腹洞穴中发现前辈修士遗骸旁留有此拳谱'
    },
    {
      id: 'gf_yunshen',
      name: '蕴神术',
      novel: '玄界之门',
      element: '神识',
      grade: '黄阶',
      desc: '温养神识的基础功法，修炼后神识范围扩大，可初步抵御精神攻击',
      cultSpeed: 1.0,
      compBonus: 2,
      mindBonus: 3,
      atkBonus: 0,
      defBonus: 0,
      realmReq: 0,
      obtain: '悟道',
      obtainDesc: '在宗门静室打坐三月，观想星辰运转后自行领悟'
    }
  ],

  // ============================================================
  // 玄阶功法（筑基期可用，修炼速度 1.5-2.0）
  // ============================================================
  xuan: [
    {
      id: 'gf_qingyuan',
      name: '青元剑诀',
      novel: '凡人修仙传',
      element: '金',
      grade: '玄阶',
      desc: '剑修入门功法，以剑气淬炼经脉，修炼后可御剑飞行，剑气凌厉无匹',
      cultSpeed: 1.6,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 8,
      defBonus: 2,
      realmReq: 1,
      obtain: '师门',
      obtainDesc: '黄枫谷筑基期核心功法，需筑基后方可入藏经阁参悟'
    },
    {
      id: 'gf_snlh',
      name: '素女轮回功',
      novel: '凡人修仙传',
      element: '水',
      grade: '玄阶',
      desc: '女修专属功法，以阴阳调和修炼，修炼后容貌不老，灵力纯净如水',
      cultSpeed: 1.7,
      compBonus: 1,
      mindBonus: 4,
      atkBonus: 2,
      defBonus: 3,
      realmReq: 1,
      obtain: '奇遇',
      obtainDesc: '古修洞府玉匣中封存，需女修纯阴之体方可开启'
    },
    {
      id: 'gf_kongshen',
      name: '控神术',
      novel: '凡人修仙传',
      element: '神识',
      grade: '玄阶',
      desc: '操控他人神识的上古秘术，修炼后可短暂控制心志不坚之人，亦可反制精神攻击',
      cultSpeed: 1.5,
      compBonus: 3,
      mindBonus: 5,
      atkBonus: 0,
      defBonus: 2,
      realmReq: 1,
      obtain: '秘境',
      obtainDesc: '乱星海秘境中上古修士遗留的玉简内记载'
    },
    {
      id: 'gf_fanjue',
      name: '焚决',
      novel: '斗破苍穹',
      element: '火',
      grade: '玄阶',
      desc: '可吞噬异火进化的奇功，修炼后体内火焰不断壮大，潜力无穷，越战越强',
      cultSpeed: 1.8,
      compBonus: 2,
      mindBonus: 1,
      atkBonus: 10,
      defBonus: 2,
      realmReq: 1,
      obtain: '奇遇',
      obtainDesc: '药老随身空间戒指中传承，需拜师方可获得'
    },
    {
      id: 'gf_guling',
      name: '骨灵冷火',
      novel: '斗破苍穹',
      element: '冰',
      grade: '玄阶',
      desc: '骨灵冷火凝聚之法，修炼后可操控极寒之火，冰火交融威力倍增，寒彻入骨',
      cultSpeed: 1.6,
      compBonus: 1,
      mindBonus: 2,
      atkBonus: 9,
      defBonus: 1,
      realmReq: 1,
      obtain: '奇遇',
      obtainDesc: '药老附身指点后传授此火之凝聚操控之法'
    },
    {
      id: 'gf_haixinyan',
      name: '海心焰',
      novel: '斗破苍穹',
      element: '水',
      grade: '玄阶',
      desc: '诞生于深海之心的奇异火焰功法，修炼后水火相济，攻防兼备',
      cultSpeed: 1.65,
      compBonus: 1,
      mindBonus: 2,
      atkBonus: 8,
      defBonus: 4,
      realmReq: 1,
      obtain: '秘境',
      obtainDesc: '深海漩涡秘境深处，海心焰自行孕育之地获得'
    },
    {
      id: 'gf_duren',
      name: '度人经',
      novel: '遮天',
      element: '光',
      grade: '玄阶',
      desc: '度化众生之法，修炼后可净化邪祟，超度亡魂，兼具攻防之效',
      cultSpeed: 1.7,
      compBonus: 3,
      mindBonus: 4,
      atkBonus: 5,
      defBonus: 5,
      realmReq: 1,
      obtain: '悟道',
      obtainDesc: '于古寺废墟中诵经三日，地涌金光，经文自行浮现'
    },
    {
      id: 'gf_taiji',
      name: '太极圣术',
      novel: '遮天',
      element: '土',
      grade: '玄阶',
      desc: '阴阳相生的圣级功法，修炼后可借天地之力化为己用，攻守平衡',
      cultSpeed: 1.75,
      compBonus: 2,
      mindBonus: 3,
      atkBonus: 6,
      defBonus: 6,
      realmReq: 1,
      obtain: '悟道',
      obtainDesc: '观太极古图三月，悟阴阳之道后自创衍生'
    },
    {
      id: 'gf_xukong',
      name: '虚空经',
      novel: '遮天',
      element: '空间',
      grade: '玄阶',
      desc: '涉及空间法则的功法，修炼后可短距离瞬移，初步掌控空间之力',
      cultSpeed: 1.6,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 4,
      defBonus: 4,
      realmReq: 1,
      obtain: '秘境',
      obtainDesc: '古墟遗迹中虚空大帝遗留的石碑上铭刻'
    },
    {
      id: 'gf_liushen',
      name: '柳神法',
      novel: '完美世界',
      element: '木',
      grade: '玄阶',
      desc: '仿柳神大道的木系功法，修炼后万木臣服，生机不灭，可借草木之力疗伤御敌',
      cultSpeed: 1.8,
      compBonus: 1,
      mindBonus: 3,
      atkBonus: 4,
      defBonus: 6,
      realmReq: 1,
      obtain: '奇遇',
      obtainDesc: '柳神化身残枝落入手中，沐浴其灵液后领悟'
    },
    {
      id: 'gf_baojian',
      name: '抱剑杀',
      novel: '完美世界',
      element: '金',
      grade: '玄阶',
      desc: '以命养剑、以剑杀敌的剑道功法，修炼后人与剑合一，一剑可破万法',
      cultSpeed: 1.55,
      compBonus: 1,
      mindBonus: 2,
      atkBonus: 12,
      defBonus: 0,
      realmReq: 1,
      obtain: '掠夺',
      obtainDesc: '击败剑修后从其剑灵空间中夺取剑谱'
    },
    {
      id: 'gf_jiuzhuan',
      name: '九转玄功',
      novel: '玄界之门',
      element: '金',
      grade: '玄阶',
      desc: '炼体玄功，九转淬炼肉身，修炼后铜皮铁骨，力大无穷，刀枪不入',
      cultSpeed: 1.7,
      compBonus: 1,
      mindBonus: 1,
      atkBonus: 6,
      defBonus: 8,
      realmReq: 1,
      obtain: '师门',
      obtainDesc: '玄界宗门筑基弟子核心功法，需通过心性考验方可修炼'
    },
    {
      id: 'gf_dali',
      name: '大力魔猿脱胎决',
      novel: '玄界之门',
      element: '土',
      grade: '玄阶',
      desc: '仿上古魔猿炼体之法，脱胎换骨后肉身堪比妖兽，力可拔山',
      cultSpeed: 1.65,
      compBonus: 0,
      mindBonus: 1,
      atkBonus: 8,
      defBonus: 7,
      realmReq: 1,
      obtain: '秘境',
      obtainDesc: '魔猿遗迹洞穴深处石壁所刻，需以妖血激活'
    },
    {
      id: 'gf_longwen',
      name: '龙纹金铠术',
      novel: '玄界之门',
      element: '金',
      grade: '玄阶',
      desc: '以龙纹铭刻金铠护体的功法，修炼后体表可凝金甲，防御力惊人',
      cultSpeed: 1.6,
      compBonus: 0,
      mindBonus: 1,
      atkBonus: 3,
      defBonus: 10,
      realmReq: 1,
      obtain: '拍卖',
      obtainDesc: '在地下黑市以重金拍得残卷，后补全龙纹缺失部分'
    }
  ],

  // ============================================================
  // 地阶功法（金丹期可用，修炼速度 2.0-3.0）
  // ============================================================
  di: [
    {
      id: 'gf_dayan',
      name: '大衍诀',
      novel: '凡人修仙传',
      element: '神识',
      grade: '地阶',
      desc: '上古神识功法，修炼后神识可分千百道，同时操控多件法器，堪称神识第一功',
      cultSpeed: 2.2,
      compBonus: 5,
      mindBonus: 6,
      atkBonus: 3,
      defBonus: 2,
      realmReq: 2,
      obtain: '悟道',
      obtainDesc: '参悟上古阵法残片，于神识枯竭之际顿悟此诀'
    },
    {
      id: 'gf_qigui',
      name: '七鬼噬魂大法',
      novel: '凡人修仙传',
      element: '暗',
      grade: '地阶',
      desc: '邪修功法，以七鬼噬魂修炼，修炼后可抽人魂魄化为己用，阴毒无比',
      cultSpeed: 2.5,
      compBonus: 2,
      mindBonus: 1,
      atkBonus: 12,
      defBonus: 0,
      realmReq: 2,
      obtain: '掠夺',
      obtainDesc: '击杀邪修后从其元神中强行搜取记忆获得'
    },
    {
      id: 'gf_qinglian',
      name: '青莲地心火',
      novel: '斗破苍穹',
      element: '火',
      grade: '地阶',
      desc: '地心深处孕育的奇异火焰功法，修炼后可操控青莲真火，焚尽万物',
      cultSpeed: 2.3,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 14,
      defBonus: 2,
      realmReq: 2,
      obtain: '秘境',
      obtainDesc: '深入地心岩浆深处，于青莲火种诞生之地收服'
    },
    {
      id: 'gf_yunluo',
      name: '陨落心炎',
      novel: '斗破苍穹',
      element: '火',
      grade: '地阶',
      desc: '天外陨石坠落所化心炎功法，修炼后心火内生可焚敌心神，防不胜防',
      cultSpeed: 2.4,
      compBonus: 1,
      mindBonus: 3,
      atkBonus: 13,
      defBonus: 1,
      realmReq: 2,
      obtain: '秘境',
      obtainDesc: '天焚炼气塔底层封印之地，破阵后方可触及火种'
    },
    {
      id: 'gf_jiumi',
      name: '九秘',
      novel: '遮天',
      element: '神识',
      grade: '地阶',
      desc: '九种秘术合一的绝学，包含临兵斗者等九字真言，修炼后攻防兼备，变化无穷',
      cultSpeed: 2.2,
      compBonus: 4,
      mindBonus: 4,
      atkBonus: 10,
      defBonus: 10,
      realmReq: 2,
      obtain: '秘境',
      obtainDesc: '九座古墓中各得一字秘，集齐后方可修炼'
    },
    {
      id: 'gf_yuantian',
      name: '源天书',
      novel: '遮天',
      element: '土',
      grade: '地阶',
      desc: '寻源断脉的至高功法，修炼后可观大地龙脉，寻天材地宝，亦可借地脉之力攻敌',
      cultSpeed: 2.0,
      compBonus: 4,
      mindBonus: 3,
      atkBonus: 6,
      defBonus: 8,
      realmReq: 2,
      obtain: '悟道',
      obtainDesc: '源天师一脉传承，需观遍天下山川大势方可参悟'
    },
    {
      id: 'gf_douzi',
      name: '斗字秘',
      novel: '遮天',
      element: '金',
      grade: '地阶',
      desc: '九秘中攻击第一的秘术，修炼后斗战之力暴增，可越阶挑战强敌',
      cultSpeed: 2.3,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 16,
      defBonus: 4,
      realmReq: 2,
      obtain: '奇遇',
      obtainDesc: '紫山中古皇遗留石壁所刻，需以战斗感悟激活'
    },
    {
      id: 'gf_jihuo',
      name: '祭火道',
      novel: '完美世界',
      element: '火',
      grade: '地阶',
      desc: '以祭火修炼火之大道的功法，修炼后可祭炼天地万火，火焰之力登峰造极',
      cultSpeed: 2.5,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 14,
      defBonus: 3,
      realmReq: 2,
      obtain: '奇遇',
      obtainDesc: '祭坛废墟中火焰图腾自行飞入眉心，传承祭火之道'
    },
    {
      id: 'gf_sanfo',
      name: '散佛八式',
      novel: '完美世界',
      element: '光',
      grade: '地阶',
      desc: '佛门至高武学，八式散佛可渡众生亦可杀众生，修炼后佛法无边，拳掌含佛光',
      cultSpeed: 2.2,
      compBonus: 3,
      mindBonus: 4,
      atkBonus: 12,
      defBonus: 8,
      realmReq: 2,
      obtain: '奇遇',
      obtainDesc: '古佛遗迹中佛骨舍利内封存，以佛力化解后方可参悟'
    },
    {
      id: 'gf_shuize',
      name: '水泽国度',
      novel: '一念永恒',
      element: '水',
      grade: '地阶',
      desc: '以水泽化国的领域功法，修炼后可展开水之领域，领域内万物皆受操控',
      cultSpeed: 2.4,
      compBonus: 2,
      mindBonus: 3,
      atkBonus: 10,
      defBonus: 10,
      realmReq: 2,
      obtain: '悟道',
      obtainDesc: '于大泽之中静坐百日，观水之百态后顿悟'
    },
    {
      id: 'gf_wandu',
      name: '万毒道典',
      novel: '一念永恒',
      element: '毒',
      grade: '地阶',
      desc: '毒修至高功法，修炼后万毒不侵，一指点出即可令方圆百里化为毒域',
      cultSpeed: 2.3,
      compBonus: 1,
      mindBonus: 2,
      atkBonus: 15,
      defBonus: 5,
      realmReq: 2,
      obtain: '秘境',
      obtainDesc: '毒谷深处毒潭底部石棺内，以万毒淬体后方可取出'
    },
    {
      id: 'gf_tongtian',
      name: '通天十八棍',
      novel: '玄界之门',
      element: '金',
      grade: '地阶',
      desc: '棍法至高功法，十八棍通天彻地，修炼后一棍可碎虚空，棍势如虹无可阻挡',
      cultSpeed: 2.1,
      compBonus: 1,
      mindBonus: 1,
      atkBonus: 18,
      defBonus: 3,
      realmReq: 2,
      obtain: '掠夺',
      obtainDesc: '击败上古棍修残魂后，从其识海中夺得棍法传承'
    },
    {
      id: 'gf_dari',
      name: '大日剑法',
      novel: '玄界之门',
      element: '光',
      grade: '地阶',
      desc: '以大日真火淬剑的剑法功法，修炼后剑光如烈日当空，一剑可焚天灭地',
      cultSpeed: 2.3,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 16,
      defBonus: 2,
      realmReq: 2,
      obtain: '悟道',
      obtainDesc: '观朝阳初升千日，剑意与大日之意共鸣后领悟'
    },
    {
      id: 'gf_longxiang',
      name: '龙象化海经',
      novel: '一念永恒',
      element: '土',
      grade: '地阶',
      desc: '以龙象之力淬炼肉身的功法，修炼后力如龙象，体内灵力如海般浩瀚',
      cultSpeed: 2.2,
      compBonus: 1,
      mindBonus: 2,
      atkBonus: 12,
      defBonus: 12,
      realmReq: 2,
      obtain: '血脉',
      obtainDesc: '觉醒远古龙象血脉后，血脉记忆中自然浮现此经'
    },
    {
      id: 'gf_hunyuan',
      name: '混元真火',
      novel: '玄界之门',
      element: '火',
      grade: '地阶',
      desc: '凝聚混元之力化为真火的功法，修炼后真火不灭，可炼化万物为元气',
      cultSpeed: 2.5,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 14,
      defBonus: 4,
      realmReq: 2,
      obtain: '秘境',
      obtainDesc: '混元秘境核心处，以自身灵力引动天地混元之气凝聚'
    },
    {
      id: 'gf_banruo',
      name: '般若天象功',
      novel: '玄界之门',
      element: '光',
      grade: '地阶',
      desc: '佛门般若功法与天象之术的结合，修炼后可化天象为攻防之力，般若智慧大增',
      cultSpeed: 2.3,
      compBonus: 4,
      mindBonus: 5,
      atkBonus: 8,
      defBonus: 8,
      realmReq: 2,
      obtain: '奇遇',
      obtainDesc: '古寺地宫中般若佛灯内封存，需以般若心经化解灯中禁制'
    }
  ],

  // ============================================================
  // 天阶功法（元婴期以上可用，修炼速度 3.0-5.0）
  // ============================================================
  tian: [
    {
      id: 'gf_mosha',
      name: '魔煞天罗功',
      novel: '凡人修仙传',
      element: '暗',
      grade: '天阶',
      desc: '上古魔道至高功法，修炼后体内魔煞化为天罗地网，困杀万物于无形',
      cultSpeed: 3.2,
      compBonus: 3,
      mindBonus: 3,
      atkBonus: 20,
      defBonus: 10,
      realmReq: 3,
      obtain: '秘境',
      obtainDesc: '魔界裂缝中上古魔修洞府内，以魔血祭开石门获得'
    },
    {
      id: 'gf_dayanqian',
      name: '大衍千诀',
      novel: '凡人修仙传',
      element: '神识',
      grade: '天阶',
      desc: '大衍诀的进阶功法，修炼后神识可达千道，同时操控千件法器，上古第一神识功法',
      cultSpeed: 3.5,
      compBonus: 8,
      mindBonus: 8,
      atkBonus: 10,
      defBonus: 8,
      realmReq: 3,
      obtain: '悟道',
      obtainDesc: '大衍诀修至大成后，于生死一线间突破极限顿悟'
    },
    {
      id: 'gf_sanqian',
      name: '三千焱炎火',
      novel: '斗破苍穹',
      element: '火',
      grade: '天阶',
      desc: '三千星辰之火凝聚的功法，修炼后可引星辰之火入体，火焰绵延三千丈',
      cultSpeed: 3.8,
      compBonus: 3,
      mindBonus: 3,
      atkBonus: 25,
      defBonus: 5,
      realmReq: 3,
      obtain: '秘境',
      obtainDesc: '星域深处星辰碎片中，以星辰之力引火种入体'
    },
    {
      id: 'gf_liudao',
      name: '六道轮回拳',
      novel: '遮天',
      element: '金',
      grade: '天阶',
      desc: '涉及轮回法则的拳法功法，六拳演化六道轮回，一拳可碎轮回',
      cultSpeed: 3.6,
      compBonus: 3,
      mindBonus: 4,
      atkBonus: 28,
      defBonus: 6,
      realmReq: 3,
      obtain: '悟道',
      obtainDesc: '参悟六道轮回古图，于轮回感悟中创出此拳'
    },
    {
      id: 'gf_taiyang',
      name: '太阳真经',
      novel: '遮天',
      element: '光',
      grade: '天阶',
      desc: '太阳圣人的至高功法，修炼后可借太阳真火修炼，光耀万丈，焚尽诸邪',
      cultSpeed: 3.5,
      compBonus: 4,
      mindBonus: 3,
      atkBonus: 22,
      defBonus: 12,
      realmReq: 3,
      obtain: '秘境',
      obtainDesc: '太阳圣殿废墟中，以太阳圣力激活圣像后传承'
    },
    {
      id: 'gf_taiyin',
      name: '太阴真经',
      novel: '遮天',
      element: '冰',
      grade: '天阶',
      desc: '太阴圣人的至高功法，修炼后可借太阴之力修炼，寒月冰封万里，至阴至寒',
      cultSpeed: 3.5,
      compBonus: 4,
      mindBonus: 4,
      atkBonus: 20,
      defBonus: 15,
      realmReq: 3,
      obtain: '秘境',
      obtainDesc: '太阴圣殿冰棺中封存，需以纯阴之体破冰取经'
    },
    {
      id: 'gf_niepan',
      name: '涅槃经',
      novel: '遮天',
      element: '火',
      grade: '天阶',
      desc: '涅槃重生之法，修炼后濒死可浴火涅槃，每次涅槃实力暴涨，不死不灭',
      cultSpeed: 4.0,
      compBonus: 3,
      mindBonus: 5,
      atkBonus: 18,
      defBonus: 18,
      realmReq: 4,
      obtain: '奇遇',
      obtainDesc: '凤凰涅槃之地，浴真火焚身重生后领悟此经'
    },
    {
      id: 'gf_bushi',
      name: '不死经',
      novel: '完美世界',
      element: '木',
      grade: '天阶',
      desc: '长生不死之术，修炼后肉身可无限再生，只要生机不绝便不死不灭',
      cultSpeed: 3.8,
      compBonus: 3,
      mindBonus: 4,
      atkBonus: 15,
      defBonus: 20,
      realmReq: 3,
      obtain: '奇遇',
      obtainDesc: '不死山中神树之心内封存，以生机之力开启'
    },
    {
      id: 'gf_liudao_tg',
      name: '六道轮回天功',
      novel: '完美世界',
      element: '金',
      grade: '天阶',
      desc: '涉及六道轮回的天级功法，修炼后可演化六道之力，轮回镇压万物',
      cultSpeed: 3.7,
      compBonus: 4,
      mindBonus: 4,
      atkBonus: 24,
      defBonus: 12,
      realmReq: 3,
      obtain: '秘境',
      obtainDesc: '六道轮回古殿中，以六道之力洗礼肉身后传承'
    },
    {
      id: 'gf_mieshi',
      name: '灭世拳',
      novel: '完美世界',
      element: '火',
      grade: '天阶',
      desc: '灭世之拳，一拳可灭一方世界，修炼后拳力蕴含灭世之意，无可阻挡',
      cultSpeed: 3.6,
      compBonus: 2,
      mindBonus: 2,
      atkBonus: 30,
      defBonus: 5,
      realmReq: 4,
      obtain: '掠夺',
      obtainDesc: '击败灭世强者残魂后，从其道果中掠夺拳意'
    },
    {
      id: 'gf_ziqi',
      name: '紫气驭鼎功',
      novel: '一念永恒',
      element: '光',
      grade: '天阶',
      desc: '以紫气驭鼎的至高功法，修炼后可驾驭天地鼎炉炼化万物，紫气东来三万里',
      cultSpeed: 3.5,
      compBonus: 5,
      mindBonus: 4,
      atkBonus: 18,
      defBonus: 15,
      realmReq: 3,
      obtain: '悟道',
      obtainDesc: '紫气东来之时，以神识捕捉紫气入体，炼化鼎炉后领悟'
    },
    {
      id: 'gf_bushijin',
      name: '不死禁',
      novel: '一念永恒',
      element: '木',
      grade: '天阶',
      desc: '不死一脉的禁忌功法，修炼后可封印生机于体内，濒死时解禁可瞬间恢复巅峰',
      cultSpeed: 3.8,
      compBonus: 3,
      mindBonus: 5,
      atkBonus: 16,
      defBonus: 22,
      realmReq: 4,
      obtain: '血脉',
      obtainDesc: '觉醒不死血脉后，血脉深处禁忌记忆自行解封'
    }
  ],

  // ============================================================
  // 仙阶/帝级功法（化神期以上可用，修炼速度 5.0-10.0）
  // ============================================================
  xian: [
    {
      id: 'gf_diyan',
      name: '帝炎',
      novel: '斗破苍穹',
      element: '火',
      grade: '仙阶',
      desc: '陀舍古帝之火，万火之尊，修炼后可操控天下万火，一念焚天灭地，火焰之极',
      cultSpeed: 7.0,
      compBonus: 5,
      mindBonus: 5,
      atkBonus: 50,
      defBonus: 20,
      realmReq: 5,
      obtain: '奇遇',
      obtainDesc: '陀舍古帝洞府中，融合天下异火后帝炎自行诞生认主'
    },
    {
      id: 'gf_xuwu',
      name: '虚无吞炎',
      novel: '斗破苍穹',
      element: '暗',
      grade: '仙阶',
      desc: '可吞噬万物的虚无之炎，修炼后火焰所过之处一切化为虚无，吞天噬地',
      cultSpeed: 6.5,
      compBonus: 4,
      mindBonus: 4,
      atkBonus: 45,
      defBonus: 15,
      realmReq: 5,
      obtain: '秘境',
      obtainDesc: '虚无空间裂缝深处，以灵魂之力降服虚无火灵'
    },
    {
      id: 'gf_jinglian',
      name: '净莲妖火',
      novel: '斗破苍穹',
      element: '火',
      grade: '仙阶',
      desc: '可净化一切的妖异之火，修炼后火焰可净化万物本源，连灵魂都可净化重塑',
      cultSpeed: 6.8,
      compBonus: 5,
      mindBonus: 6,
      atkBonus: 42,
      defBonus: 25,
      realmReq: 5,
      obtain: '秘境',
      obtainDesc: '净莲妖火封印之地，以纯善之心度化妖火后方可收服'
    },
    {
      id: 'gf_wushi',
      name: '无始经',
      novel: '遮天',
      element: '神识',
      grade: '仙阶',
      desc: '无始大帝的至高功法，修炼后可窥时间初始之秘，一念镇压万物，无始无终',
      cultSpeed: 8.0,
      compBonus: 10,
      mindBonus: 10,
      atkBonus: 35,
      defBonus: 35,
      realmReq: 6,
      obtain: '悟道',
      obtainDesc: '无始大帝铜殿深处，以无始之气洗礼元神后自行传承'
    },
    {
      id: 'gf_tiandi',
      name: '天帝拳',
      novel: '遮天',
      element: '光',
      grade: '仙阶',
      desc: '天帝所创至高拳法，修炼后拳含天帝之意，一拳可碎星辰日月，帝威盖世',
      cultSpeed: 7.5,
      compBonus: 5,
      mindBonus: 5,
      atkBonus: 55,
      defBonus: 15,
      realmReq: 6,
      obtain: '奇遇',
      obtainDesc: '天帝陵寝中天帝虚影传拳，需以战意打动天帝残念'
    },
    {
      id: 'gf_bumietian',
      name: '不灭天功',
      novel: '遮天',
      element: '土',
      grade: '仙阶',
      desc: '不灭大帝的至高功法，修炼后肉身不灭，纵使天地崩毁亦不伤分毫，至强防御',
      cultSpeed: 6.0,
      compBonus: 4,
      mindBonus: 5,
      atkBonus: 25,
      defBonus: 50,
      realmReq: 5,
      obtain: '血脉',
      obtainDesc: '觉醒不灭血脉后，血脉至深处不灭道果自行觉醒'
    },
    {
      id: 'gf_busicg',
      name: '不死长生亘古功',
      novel: '一念永恒',
      element: '木',
      grade: '仙阶',
      desc: '亘古长生的至高功法，修炼后与天地同寿，生机绵绵不绝，不死不灭长生万古',
      cultSpeed: 8.5,
      compBonus: 6,
      mindBonus: 8,
      atkBonus: 30,
      defBonus: 40,
      realmReq: 6,
      obtain: '悟道',
      obtainDesc: '亘古之地观天地生灭一轮回，悟长生大道后自创'
    },
    {
      id: 'gf_kunpeng',
      name: '鲲鹏法',
      novel: '完美世界',
      element: '空间',
      grade: '仙阶',
      desc: '鲲鹏至高功法，修炼后可化鲲化鹏，扶摇直上九万里，速度天下第一，空间法则尽掌',
      cultSpeed: 7.0,
      compBonus: 6,
      mindBonus: 5,
      atkBonus: 40,
      defBonus: 30,
      realmReq: 5,
      obtain: '奇遇',
      obtainDesc: '鲲鹏巢穴中鲲鹏真血认主，沐浴真血后传承鲲鹏法'
    }
  ],

  // ============================================================
  // 圣阶功法（真仙至准圣境界可用，realmReq 9-13，修炼速度 8.0-15.0）
  // 来源：封神演义、洪荒流、西游记等
  // ============================================================
  sheng: [
    {
      id: 'gf_hunyuandaode',
      name: '混元道德真经',
      novel: '封神演义',
      element: '悟性',
      grade: '圣阶',
      desc: '太上老君所传至高道经，混元无极道德无双，修炼后悟性通天，可参悟大道本源万法归一',
      cultSpeed: 14.0,
      compBonus: 25,
      mindBonus: 22,
      atkBonus: 80,
      defBonus: 80,
      realmReq: 13,
      obtain: '悟道',
      obtainDesc: '老君讲道紫霄宫时，以纯净道心聆听三天三夜后自行领悟'
    },
    {
      id: 'gf_yuanshizhenjing',
      name: '原始真经',
      novel: '封神演义',
      element: '空间',
      grade: '圣阶',
      desc: '元始天尊所传至高真经，掌控空间本源法则，修炼后可开辟天地，一念挪移诸天万界',
      cultSpeed: 13.5,
      compBonus: 20,
      mindBonus: 20,
      atkBonus: 92,
      defBonus: 70,
      realmReq: 13,
      obtain: '秘境',
      obtainDesc: '玉虚宫深处混沌秘境中，以元始符诏开启玉匣后传承'
    },
    {
      id: 'gf_lingbaozhenjing',
      name: '灵宝真经',
      novel: '封神演义',
      element: '剑',
      grade: '圣阶',
      desc: '通天教主所传剑道至高真经，诛仙四剑之意尽在其中，修炼后一剑可斩诸天圣人',
      cultSpeed: 13.0,
      compBonus: 18,
      mindBonus: 16,
      atkBonus: 115,
      defBonus: 52,
      realmReq: 13,
      obtain: '奇遇',
      obtainDesc: '碧游宫剑冢深处，诛仙剑意自行择主，以剑心契合后传承'
    },
    {
      id: 'gf_wanjiezhenjing',
      name: '万劫真经',
      novel: '西游记',
      element: '雷',
      grade: '圣阶',
      desc: '玉皇大帝历经万劫所悟真经，修炼后可御万劫天雷，历劫不灭越劫越强',
      cultSpeed: 11.5,
      compBonus: 16,
      mindBonus: 18,
      atkBonus: 96,
      defBonus: 60,
      realmReq: 12,
      obtain: '悟道',
      obtainDesc: '历经一千七百五十劫，每劫十二万九千六百年后于雷劫中顿悟'
    },
    {
      id: 'gf_zaohuabaodian',
      name: '造化宝典',
      novel: '洪荒流',
      element: '混沌',
      grade: '圣阶',
      desc: '鸿钧老祖所传造化至高宝典，掌控混沌造化之力，修炼后可造化天地化无为有',
      cultSpeed: 15.0,
      compBonus: 24,
      mindBonus: 24,
      atkBonus: 85,
      defBonus: 90,
      realmReq: 13,
      obtain: '悟道',
      obtainDesc: '紫霄宫三次讲道，得鸿钧老祖亲传造化玉牒残片后参悟'
    },
    {
      id: 'gf_taijidadao',
      name: '太极大道',
      novel: '封神演义',
      element: '阴阳',
      grade: '圣阶',
      desc: '老子所悟太极大道，阴阳相生相克，修炼后可执掌阴阳本源，太极归一万法不侵',
      cultSpeed: 12.0,
      compBonus: 20,
      mindBonus: 20,
      atkBonus: 75,
      defBonus: 78,
      realmReq: 12,
      obtain: '悟道',
      obtainDesc: '观太极古图百年，阴阳二气于丹田交汇后自行领悟'
    },
    {
      id: 'gf_qiankundanuoyi',
      name: '乾坤大挪移',
      novel: '洪荒流',
      element: '空间',
      grade: '圣阶',
      desc: '上古空间至高神功，修炼后可挪移乾坤扭转天地法则，借力打力无往不利',
      cultSpeed: 9.0,
      compBonus: 14,
      mindBonus: 15,
      atkBonus: 72,
      defBonus: 58,
      realmReq: 10,
      obtain: '秘境',
      obtainDesc: '上古神殿废墟中枢祭坛，以空间感悟激活乾坤阵眼后获得'
    },
    {
      id: 'gf_jiuzhuanxuangong_sage',
      name: '九转玄功',
      novel: '封神演义',
      element: '金',
      grade: '圣阶',
      desc: '杨戬所修至高炼体神功，九转之后肉身成圣，力可担山赶月，八九玄功通天彻地',
      cultSpeed: 10.0,
      compBonus: 12,
      mindBonus: 13,
      atkBonus: 102,
      defBonus: 72,
      realmReq: 11,
      obtain: '血脉',
      obtainDesc: '觉醒杨氏血脉中上古玄功记忆，以九转之力淬体后方可修成'
    },
    {
      id: 'gf_tiangan36bian',
      name: '天罡三十六变',
      novel: '西游记',
      element: '风',
      grade: '圣阶',
      desc: '上古天罡变化神功，三十六般变化随心所欲，修炼后可千变万化移星换斗',
      cultSpeed: 9.5,
      compBonus: 15,
      mindBonus: 14,
      atkBonus: 74,
      defBonus: 56,
      realmReq: 10,
      obtain: '奇遇',
      obtainDesc: '天罡星域古阵中，三十六天罡星力洗礼肉身后传承'
    },
    {
      id: 'gf_disha72bian',
      name: '地煞七十二变',
      novel: '西游记',
      element: '土',
      grade: '圣阶',
      desc: '上古地煞变化神功，七十二般变化玄妙无穷，修炼后可通天彻地变化万端',
      cultSpeed: 9.5,
      compBonus: 15,
      mindBonus: 14,
      atkBonus: 70,
      defBonus: 64,
      realmReq: 10,
      obtain: '奇遇',
      obtainDesc: '幽冥地脉深处地煞源眼，七十二地煞之力灌体后领悟'
    },
    {
      id: 'gf_hunyuandaluo',
      name: '混元大罗金仙功',
      novel: '洪荒流',
      element: '混沌',
      grade: '圣阶',
      desc: '修至混元大罗金仙之境的至高功法，修炼后与道合真超脱因果，万劫不灭永恒不朽',
      cultSpeed: 14.5,
      compBonus: 24,
      mindBonus: 23,
      atkBonus: 88,
      defBonus: 88,
      realmReq: 13,
      obtain: '悟道',
      obtainDesc: '证道混元之际，天道降下金仙果位，于果位中悟得此功'
    },
    {
      id: 'gf_zhansanshi',
      name: '斩三尸之法',
      novel: '洪荒流',
      element: '神识',
      grade: '圣阶',
      desc: '斩却善恶执念三尸的至高秘法，修炼后可斩尸证道，元神纯净通明直指大道',
      cultSpeed: 11.0,
      compBonus: 23,
      mindBonus: 26,
      atkBonus: 78,
      defBonus: 66,
      realmReq: 12,
      obtain: '悟道',
      obtainDesc: '于紫霄宫听道后悟得斩尸之理，以先天灵宝寄托执念方可修成'
    },
    {
      id: 'gf_liangjiejing',
      name: '量劫经',
      novel: '洪荒流',
      element: '雷',
      grade: '圣阶',
      desc: '参悟天地量劫之理的至高功法，修炼后可引动量劫之力，以劫炼身以劫证道',
      cultSpeed: 10.5,
      compBonus: 15,
      mindBonus: 17,
      atkBonus: 94,
      defBonus: 54,
      realmReq: 11,
      obtain: '秘境',
      obtainDesc: '无量量劫遗迹核心，劫灰凝聚的经文需以劫雷淬炼后方可参悟'
    },
    {
      id: 'gf_honghuangzaohua',
      name: '洪荒造化功',
      novel: '洪荒流',
      element: '木',
      grade: '圣阶',
      desc: '洪荒时代造化之力的至高功法，修炼后可唤洪荒生机，一念草木成林造化生生不息',
      cultSpeed: 10.0,
      compBonus: 18,
      mindBonus: 17,
      atkBonus: 76,
      defBonus: 74,
      realmReq: 11,
      obtain: '奇遇',
      obtainDesc: '洪荒建木残根之中，以造化生机激活根须后传承'
    },
    {
      id: 'gf_zhutianwanjie',
      name: '诸天万界法',
      novel: '洪荒流',
      element: '空间',
      grade: '圣阶',
      desc: '洞悉诸天万界法则的至高功法，修炼后可穿梭万界，借诸天之力为己用法力无边',
      cultSpeed: 12.5,
      compBonus: 20,
      mindBonus: 19,
      atkBonus: 82,
      defBonus: 68,
      realmReq: 12,
      obtain: '悟道',
      obtainDesc: '穿梭诸天万界感悟各界法则，集万界之理于一身后顿悟'
    },
    {
      id: 'gf_rulai',
      name: '如来大乘真经',
      novel: '西游记',
      element: '光',
      grade: '圣阶',
      desc: '如来佛祖所证无上大乘真经，万德庄严佛光普照，修炼后可渡化万类一念成佛，法力无边佛威无量',
      cultSpeed: 11.0,
      compBonus: 20,
      mindBonus: 25,
      atkBonus: 76,
      defBonus: 82,
      realmReq: 9,
      obtain: '师门',
      obtainDesc: '大雷音寺佛祖讲经时，以菩提心聆听如来真实义后传承'
    },
    {
      id: 'gf_wanfo',
      name: '万佛朝宗经',
      novel: '洪荒流',
      element: '光',
      grade: '圣阶',
      desc: '万佛齐聚之无上佛门功法，修炼后可号令万佛之力，万佛朝宗佛威浩荡，横扫一切邪魔外道',
      cultSpeed: 12.5,
      compBonus: 22,
      mindBonus: 22,
      atkBonus: 88,
      defBonus: 72,
      realmReq: 10,
      obtain: '师门',
      obtainDesc: '万佛宗万佛殿中，以佛心引动万佛法相后传承'
    },
    {
      id: 'gf_xiuluo',
      name: '修罗杀道',
      novel: '洪荒流',
      element: '暗',
      grade: '圣阶',
      desc: '阿修罗道统所传至杀之道，以杀证道以战养战，修炼后杀气冲霄战力无双，可化修罗战身横扫诸天',
      cultSpeed: 10.5,
      compBonus: 14,
      mindBonus: 8,
      atkBonus: 120,
      defBonus: 58,
      realmReq: 9,
      obtain: '师门',
      obtainDesc: '修罗宗修罗血池深处，以修罗杀血洗礼后传承'
    },
    {
      id: 'gf_tianmo',
      name: '天魔乱道经',
      novel: '洪荒流',
      element: '暗',
      grade: '圣阶',
      desc: '天魔道统至高秘典，修炼后可化万千天魔分身，乱天动地扰人心神，以魔乱道万法皆空',
      cultSpeed: 11.5,
      compBonus: 16,
      mindBonus: 10,
      atkBonus: 100,
      defBonus: 55,
      realmReq: 10,
      obtain: '师门',
      obtainDesc: '天魔宗天魔殿天魔源眼中，以天魔之力洗礼后传承'
    },
    {
      id: 'gf_zaozao',
      name: '造化天道',
      novel: '洪荒流',
      element: '混沌',
      grade: '圣阶',
      desc: '参悟造化本源天道之无上功法，修炼后可造化万物衍化天地，无中生有化虚为实，直指造化大道本源',
      cultSpeed: 13.0,
      compBonus: 22,
      mindBonus: 24,
      atkBonus: 82,
      defBonus: 85,
      realmReq: 10,
      obtain: '悟道',
      obtainDesc: '于造化玉牒残片前参悟造化本源，以道心共鸣后顿悟'
    }
  ]

};

// ============================================================
// 导出
// ============================================================
if (typeof module !== 'undefined' && module.exports) {
  module.exports = GONGFA_DATA;
}
if (typeof window !== 'undefined') {
  window.GONGFA_DATA = GONGFA_DATA;
}
